name: Android CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decoded secrets
        env:
          ENCODED_SECURE_FILE: ${{ secrets.ENCODED_SECURE_FILE }}
        run: |
#          mkdir "${GITHUB_WORKSPACE}"/app/src/main/java/com/uogames/balinasoft/test/
          echo $ENCODED_SECURE_FILE | base64 -di "${GITHUB_WORKSPACE}"/app/src/main/java/com/uogames/balinasoft/test/Secured.Kt


      - name: Clean build
        run: ./gradlew clean

      - name: Build bundle apk
        run: ./gradlew app:assembleDebug

